# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c192c6289c9db020459d8aae22557520b0c8d1c7c5507a4d81ee40b5a3a30f8686f198938bc4466289f455e3a8ea1dbc5f78111cc548aa360c265ee746578bd7

test:
  secret_key_base: 7eb5703701e2f7d05dc8dd0669159e57fa057aae0f9056e2ca2cb87f3e38420419d098b9913343ea92c1dd6b1a4b78e2e904b915cab8b728bf64bfc107e96c65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
